id: P009541
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG8537
  title: རྒྱལ་བ་གནས་མདོ་པའི་བླ་བརྒྱུད་དང་དམ་པའི་ཆོས་ཀྱི་བྱུང་བ་མདོར་བསྡུས་དྭངས་ཤེལ་མེ་ལོང་།
  author: ''
  volumes:
    3137e9d0af36407ca151994d6a666706:
      image_group_id: I1KG8573
      title: ''
      volume_number: 1
      total_pages: 210
      base_file: v001.txt
