id: opecha:P009541
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG8537
  title: རྒྱལ་བ་གནས་མདོ་པའི་བླ་བརྒྱུད་དང་དམ་པའི་ཆོས་ཀྱི་བྱུང་བ་མདོར་བསྡུས་དྭངས་ཤེལ་མེ་ལོང་།
  volume: ''
  author: ''
