id: I3342AF51
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T21:31:21+00:00'
last_modified: '2022-06-08T11:45:42.379303+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG8537
  title: རྒྱལ་བ་གནས་མདོ་པའི་བླ་བརྒྱུད་དང་དམ་པའི་ཆོས་ཀྱི་བྱུང་བ་མདོར་བསྡུས་དྭངས་ཤེལ་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F46F:
      image_group_id: I1KG8573
      title: ''
      total_pages: 210
      order: 1
      base_file: F46F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
